Allow specifying an array or string for mount
donny-dont/drone-cache pull request #2
Opened 2016-12-06 03:08 UTC by jmccann

* Set `plugin.Mount` from `string` to `[]string`
* Converted functions using the mount as a `src` to take `[]string` instead of `string`
* In tar.go loop through the `srcs` and call `filepath.Walk` for each element

Also includes minor update to `make(chan error)` to be `make(chan error, 1)` to prevent hanging when Get/Put functions return an error.

2016-12-06 05:27 UTC, donny-dont requested changes

2016-12-06 05:27 UTC, donny-dont commented on plugin/cli.go
> +		mount = strings.Split(c.GlobalString(mountFlag), ",")
Theres a StringSliceFlag so the split isn't required.

2016-12-06 05:27 UTC, donny-dont commented on archive/tar.go
> +		fwErr = filepath.Walk(s, func(path string, fi os.FileInfo, err error) error {
Looks like `fwErr` will be overwritten on each iteration of the loop so it will only return the last value set.

2016-12-06 13:12 UTC, jmccann commented on archive/tar.go
> +		fwErr = filepath.Walk(s, func(path string, fi os.FileInfo, err error) error {
I pushed an update to return on each loop ... let me know if there is something better.  😄

2016-12-07 21:38 UTC, donny-dont requested changes

2016-12-07 21:38 UTC, donny-dont commented on archive/tar.go
> +		return fwErr
Shouldnt this be an if check?

2016-12-07 21:46 UTC, jmccann commented
@donny-dont Think I got it fixed now

2016-12-07 21:47 UTC, donny-dont approved these changes

2016-12-07 21:47 UTC, merged