Remove fixture files from repo and instead generate them from code
donny-dont/drone-cache pull request #7
Opened 2016-12-14 16:12 UTC by jmccann

Trying to remove fixtures directory and generate what is needed from code.

2016-12-14 18:02 UTC, donny-dont requested changes
So here's what I imagined for doing stuff without fixtures

For writing
* Setup would create the files in a temp directory somewhere.
* Tar file would be written
* Examine the contents of it through a reader

For reading
* Take the previous tar file and expand it
* Make sure everything is written out the same way

2016-12-14 18:02 UTC, donny-dont commented on archive/tar/tar_test.go
> +func createGoodTarfile() {
I'm a bit confused as to why this is here. Shouldn't it just write the files and then the tar code creates the tar.

2016-12-14 19:23 UTC, jmccann commented
Thanks for the direction.  Will get it implemented.

2016-12-14 21:28 UTC, jmccann commented
So here's what I implemented

For writing
* Setup creates the files in a temp directory somewhere.
* Tar file would be written

For reading
* Take the previous tar file and expand it
* Make sure everything is written out the same way

Still missing cause I'm not sure how
* Examine the tar file contents through a reader.

Let me know you thoughts on what I did so far.  Also was wondering if you could help on the missing item or if we could just skip it for now since Unpack checks sort of verify that part as well (though it doesn't keep the testing for things in their own set of tests I admit).

2016-12-15 00:03 UTC, donny-dont approved these changes

2016-12-15 00:03 UTC, merged